version: 2.1

orbs:
  android: circleci/android@1.0

commands:
  init-fastlane:
    parameters:
    steps:
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  assembleDebug:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - init-fastlane
      - run:
          name: Assemble debug build
          command: |
            bundle exec fastlane beta
      - persist_to_workspace:
          root: app/build/outputs/apk
          paths:
            - debug
      - store_artifacts:
          path: app/build/outputs/apk/debug
      - android/save-gradle-cache
      - android/save-build-cache

  unit-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - init-fastlane
      - android/run-tests:
          test-command: bundle exec fastlane test
      - android/save-gradle-cache
      - android/save-build-cache

  lint:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - run:
          name: Install ktlint
          command: |
            curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint &&
              chmod a+x ktlint &&
              sudo mv ktlint /usr/local/bin
      - run:
          name: Run ktlint
          command: |
            ktlint ./**/*.kt

  publish-to-github:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./apk
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./apk/**/*.apk

workflows:
  build-and-test:
    jobs:
      - assembleDebug:
          filters:
            tags:
              only: /.*/
      - lint
#      - unit-test:
#          requires:
#            - assembleDebug
      - publish-to-github:
          requires:
            - assembleDebug
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
