version: 2.1

orbs:
  android: circleci/android@1.0

jobs:
  assembleDebug:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Setup Gradle permissions
          commans: |
          chmod +x gradlew
      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug
      - android/save-gradle-cache
      - android/save-build-cache

  unit-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache

workflows:
  build:
    jobs:
      - assembleDebug
