version: 2.1

orbs:
  android: circleci/android@1.0

jobs:
  assembleDebug:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Setup Gradle permissions
          command: |
            chmod +x gradlew
      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug
      - android/save-gradle-cache
      - android/save-build-cache

  unit-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache

  lint:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - run:
          name: Install ktlint
          command: |
            curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint &&
              chmod a+x ktlint &&
              sudo mv ktlint /usr/local/bin
      - run:
          name: Run ktlint
          command: |
            ktlint ./**/*.kt

workflows:
  build:
    jobs:
      - assembleDebug
  lint:
    jobs:
      - lint
